Motion Mint/Models/Returncar.cs
namespace Motion_Mint.Models
{
    public partial class Returncar
    {
        public int Id { get; set; }
        public string ? Carno { get; set; }

        public int ? Custid { get; set; }
       
        public DateOnly ? Date { get; set; }

        public int ? Elsp { get; set; }

        public int? Fine { get; set; }


    }
}

Motion Mint/Controllers/ReturncarController.cs
using Microsoft.AspNetCore.Mvc;

namespace Motion_Mint.Controllers
{
    public class ReturncarController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Motion Mint/Views/Returncar/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@

@{
    ViewData["Title"] = "Index";
}
<div class="container mt-5">
    @using (Html.BeginForm("Save", "Returncar", FormMethod.Post, new { id = "popupForm" }))
    {
        <div class="card">
            <div class="card-body">
                <h1 class="card-title">Car Rental</h1>

                <div class="form-group">
                    <label class="form-label">Car Number</label>
                    <input type="text" id="carid" name="carid" class="form-control" placeholder="Car Number" required>
                    
                </div>

                <div class="form-group">
                    <label class="form-label">Customer ID</label>
                    <input type="text" id="custid" name="custid" class="form-control" placeholder="Customer ID" required>
                </div>

                <div class="form-group">
                    <label class="form-label">Date</label>
                    <input type="date" id="date" name="date" class="form-control" placeholder="Customer Name" required>
                </div>

                <div class="form-group">
                    <label class="form-label">Days Elapsed</label>
                    <input type="text" id="elsp" name="elsp" class="form-control" placeholder="Rental Fee" required>
                </div>

                <div class="form-group">
                    <label class="form-label">Fine</label>
                    <input type="text" id="fine" name="fine" class="form-control" placeholder="Start Date" required>
                </div>

                <br />
                <div class="text-center">
                    <input type="submit" value="Save" class="btn btn-success" />
                </div>

            </div>
        </div>
    }
</div>



@section scripts
{
    <script src="~/Scripts/jquery-1.10.2.js"></script>
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>

    <script>
       









    </script>
}