Motion Mint/Models/Rental.cs
using System;
using System.Collections.Generic;

namespace Motion_Mint.Models;

public partial class Rental
{
    public int Id { get; set; }

    public string? Carid { get; set; }

    public int? Custid { get; set; }

    public int? Fee { get; set; }

    public DateOnly? Sdate { get; set; }

    public DateOnly? Edate { get; set; }
}

Motion Mint/Controllers/RentalController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Motion_Mint.Models;
using System;
using System.Linq;
namespace Motion_Mint.Controllers
{
    public class RentalController : Controller
    {
        MotionMintContext db = new MotionMintContext();

        public ActionResult Index()
        {
           return View();
        }

        [HttpGet]
        public IActionResult GetCar()
        {
            var cars = db.Carregs.ToList();
            return Json(cars);
        }


        [HttpPost]
        public IActionResult Getid(int? id)
        {
            var customer = db.Customers
                             .Where(s => s.Id == id)
                             .Select(s => s.Custname)
                             .FirstOrDefault();
            return Json(customer);
        }


        [HttpPost]
        public IActionResult Getavil(string carno)
        {
            var car = db.Carregs
                        .Where(c => c.Carno == carno)
                        .Select(c => c.Available)
                        .FirstOrDefault();

            return Json(car);
        }


        [HttpPost]
        public async Task<IActionResult> Save(Rental rent)
        {
            Console.WriteLine(rent.Carid + " " + rent.Custid + " " + rent.Id);
            try
            {
                {
                    {
                        db.Rentals.Add(rent);
                        await db.SaveChangesAsync();
                        return View("details", rent);

                        //db.Rentals.Add(rent);
                        //db.SaveChanges(); 


                        //var car = db.Carregs.SingleOrDefault(e => e.Carno == rent.Carid);
                        //if (car == null)
                        //{
                        //    return NotFound("Car number is not valid");
                        //}
                        //car.Available = "No";
                        //db.Entry(car).State = EntityState.Modified; 
                        //db.SaveChanges(); 

                        return RedirectToAction("Index");
                    }


                    return View(rent);
                }
            }
            catch (Exception ex)
            {
                // Log the exception
                Console.WriteLine($"Exception occurred: {ex.Message}");
                if (ex.InnerException != null)
                {
                    Console.WriteLine($"Inner exception: {ex.InnerException.StackTrace}");
                    if (ex.InnerException.InnerException != null)
                    {
                        Console.WriteLine($"Inner inner exception: {ex.InnerException.StackTrace}");
                    }
                }
                return StatusCode(500, $"An error occurred while processing your request: {ex.Message}");
            }
        }


    }
}

Motion Mint/Views/Rental/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Index";
}


<div class="container mt-5">
    @using (Html.BeginForm("Save", "Rental", FormMethod.Post, new { id = "popupForm" }))
    {
        <div class="card">
            <div class="card-body">
                <h1 class="card-title">Car Rental</h1>

                <div class="form-group">
                    <label class="form-label">Car Number</label>
                    <select class="form-control" id="carid" name="carid" placeholder="Car Number" required>
                        <option>Please Select</option>
                    </select>
                </div>

                <div class="form-group">
                    <label class="form-label">Customer ID</label>
                    <input type="text" id="custid" name="custid" class="form-control" placeholder="Customer ID" required>
                </div>

                <div class="form-group">
                    <label class="form-label">Customer Name</label>
                    <input type="text" id="custname" name="custname" class="form-control" placeholder="Customer Name" required>
                </div>

                <div class="form-group">
                    <label class="form-label">Rental Fee</label>
                    <input type="text" id="fee" name="fee" class="form-control" placeholder="Rental Fee" required>
                </div>

                <div class="form-group">
                    <label class="form-label">Start Date</label>
                    <input type="date" id="sdate" name="sdate" class="form-control" placeholder="Start Date" required>
                </div>

                <div class="form-group">
                    <label class="form-label">End Date</label>
                    <input type="date" id="edate" name="edate" class="form-control" placeholder="End Date" required>
                </div>
                <br />
                <div class="text-center">
                    <input type="submit" value="Save" class="btn btn-success" />
                </div>

            </div>
        </div>
    }
</div>

@section scripts
{
    <script src="~/Scripts/jquery-1.10.2.js"></script>
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>

    <script>
        $(document).ready(function () {

            function load() {
                $("#custid").attr("disabled", "disabled");
                $("#custname").attr("disabled", "disabled");
                $("#fee").attr("disabled", "disabled");
                $("#sdate").attr("disabled", "disabled");
                $("#edate").attr("disabled", "disabled");
            }

            function getCar() {
                $.ajax({
                    type: 'GET',
                    url: '/Rental/GetCar',
                    dataType: 'json',
                    success: function (data) {
                        console.log(data);
                        for (var i = 0; i < data.length; i++) {
                            $("#carid").append($("<option/>", {
                                value: data[i].carno,
                                text: data[i].carno
                            }));
                        }
                    },
                    error: function (error) {
                        console.error('Error fetching cars:', error);
                    }
                });
            }

            function getCustomer() {
                $('#custid').keyup(function () {
                    var id = $(this).val();
                    if (id) {
                        $.ajax({
                            type: 'POST',
                            url: '/Rental/Getid',
                            data: { id: id },
                            dataType: 'json',
                            success: function (data) {
                                console.log(data);
                                $('#custname').val(data);
                            },
                            error: function (error) {
                                console.error('Error fetching customer:', error);
                            }
                        });
                    }
                });
            }

            $("#carid").change(function () {
                available();
            });

            function available() {
                $.ajax({
                    type: 'POST',
                    url: '/Rental/Getavil',
                    data: { carno: $("#carid").val() },
                    dataType: 'json',
                    success: function (data) {
                        console.log(data);
                        var aval = data;
                        if (aval == "Yes") {
                            $("#custid").removeAttr('disabled');
                            $("#custname").removeAttr('disabled');
                            $("#fee").removeAttr('disabled');
                            $("#sdate").removeAttr('disabled');
                            $("#edate").removeAttr('disabled');
                        } else {
                            $("#custid").attr("disabled", "disabled");
                            $("#custname").attr("disabled", "disabled");
                            $("#fee").attr("disabled", "disabled");
                            $("#sdate").attr("disabled", "disabled");
                            $("#edate").attr("disabled", "disabled");
                        }
                    },
                    error: function (error) {
                        console.error('Error checking availability:', error);
                    }
                });
            }

            getCar();
            load();
            getCustomer();
        });
    </script>
}

Motion Mint/Views/Rental/details.cshtml
@model Motion_Mint.Models.Rental

@{
    ViewData["Title"] = "View";
}

<h1>View</h1>

<div>
    <h4>Rental</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Carid)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Carid)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Custid)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Custid)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Fee)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Fee)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Sdate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Sdate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Edate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Edate)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Create"></a> |
    <a asp-action="Index">Back to List</a>
</div>